models:
  target: "Qwen/Qwen2.5-7B-Instructc"
  investigator: "meta-llama/Llama-3.1-8B"
  judge: "Qwen/Qwen2.5-32B-Instruct-AWQ"


serving:
  host: "localhost"
  target_port: 8000,
  judge_port: 8000,
