defaults:
  - ppo_trainer
  - _self_

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false

data:
  train_files: prepared/train.parquet
  val_files: prepared/train.parquet
  train_batch_size: 1
  max_prompt_length: 2048
  max_response_length: 1024
  filter_overlong_prompts: true

actor_rollout_ref:
  model:
    path: Qwen/Qwen2.5-3B-Instruct
    use_remove_padding: true
    enable_gradient_checkpointing: true 
  actor:
    optim:
      lr: 1e-6
    ppo_mini_batch_size: 1
    ppo_micro_batch_size_per_gpu: 4
    kl_loss_coef: 0.001
    strategy: fsdp
    fsdp_config:
      param_offload: false
      optimizer_offload: false
      model_dtype: bf16
  rollout:
    name: vllm
    n: 16
    max_model_len: 1024
    tensor_model_parallel_size: 1
    max_num_seqs: 64
    gpu_memory_utilization: 0.5
    log_prob_micro_batch_size_per_gpu: 8
    engine_kwargs:
      vllm:
        max_model_len: 2048
        enable_prefix_caching: true
  ref:
    log_prob_micro_batch_size_per_gpu: 8
    fsdp_config:
      param_offload: false

reward_model:
  reward_manager: naive

custom_reward_function:
  path: src/reward_wrapper.py
  name: compute_score

trainer:
  balance_batch: true
  logger: ["console", "wandb"]
  project_name: transluce_repro
  experiment_name: qwen_25_3b_run
  n_gpus_per_node: 1
  total_epochs: 200
  val_before_train: false
  test_freq: -1
  save_freq: 30
  default_local_dir: saved_models/qwen-2_5-3b-grpo
